# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PyQt5\PyQt558\main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(966, 635)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBox_food = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_food.setMinimum(100)
        self.spinBox_food.setMaximum(10000)
        self.spinBox_food.setSingleStep(100)
        self.spinBox_food.setProperty("value", 1500)
        self.spinBox_food.setObjectName("spinBox_food")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_food)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBox_rent = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_rent.setMinimum(100)
        self.spinBox_rent.setMaximum(10000)
        self.spinBox_rent.setSingleStep(100)
        self.spinBox_rent.setProperty("value", 2000)
        self.spinBox_rent.setObjectName("spinBox_rent")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_rent)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spinBox_electricity = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_electricity.setMinimum(100)
        self.spinBox_electricity.setMaximum(1000)
        self.spinBox_electricity.setSingleStep(50)
        self.spinBox_electricity.setProperty("value", 500)
        self.spinBox_electricity.setObjectName("spinBox_electricity")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_electricity)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.spinBox_traffic = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_traffic.setMinimum(100)
        self.spinBox_traffic.setMaximum(2000)
        self.spinBox_traffic.setSingleStep(50)
        self.spinBox_traffic.setProperty("value", 300)
        self.spinBox_traffic.setObjectName("spinBox_traffic")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_traffic)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.spinBox_relationship = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_relationship.setMinimum(100)
        self.spinBox_relationship.setMaximum(3000)
        self.spinBox_relationship.setSingleStep(100)
        self.spinBox_relationship.setProperty("value", 500)
        self.spinBox_relationship.setObjectName("spinBox_relationship")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_relationship)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.spinBox_taobao = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_taobao.setMinimum(100)
        self.spinBox_taobao.setMaximum(10000)
        self.spinBox_taobao.setSingleStep(50)
        self.spinBox_taobao.setProperty("value", 300)
        self.spinBox_taobao.setObjectName("spinBox_taobao")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox_taobao)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "微信公众号：学点编程吧--饼形图"))
        self.groupBox.setTitle(_translate("Form", "消费类别"))
        self.label.setText(_translate("Form", "伙食消费"))
        self.label_2.setText(_translate("Form", "房屋租金"))
        self.label_5.setText(_translate("Form", "水电气"))
        self.label_3.setText(_translate("Form", "交通费用"))
        self.label_4.setText(_translate("Form", "人情往来"))
        self.label_6.setText(_translate("Form", "淘宝网购"))
        self.checkBox.setText(_translate("Form", "自动演示"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

